### ISSUE TITLE
Consolidate 'nutritional restriction/avoidance' tickets and add to pattern(s)

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#112]
Trying to consolidate several tickets. Will close tickets, but go back to closed tickets for defs/PMID xrefs.
#82 #83 #93 #4 #48 # #95 

  | Term | In MAXO | Notes:
-- | -- | -- | --
-   [x] | isoleucine restricted diet | no |  
-   [ ] | dietary precursor restriction diet | no |  
-   [x] | dietary protein restricion | yes |  
-   [ ] | Iron chelation | no |  
-   [x] | arginine restriction (or avoidance?) | no |  
-   [x] | lysine restriction | no |  
-   [x] | methione restriction | no |  
-   [x] | glycine restriction | no |  
-   [x] | Dietary restriction branched   amino-acids | no |  
-   [x] | phenylalanine restriction | yes | #82
-   [ ] | low fat diet | no |  
-   [x] | tyrosine restriction | no | #82
-   [ ] | fasting avoidance | yes |  
-   [x] | gluten   avoidance |   | #83
-   [x] | Sodium   avoidance |   | #83
-   [x] | galactose free diet | no | #93
-   [x] | cholesterol restriction |   |  
-   [x] | ascorbate restriction |   | #48
-   [x] | iron restriction |   | #48
-   [x] | ascorbic acid restriction |   | #48
-   [x] | branched chain amino acid   restriction | #95

**Comment by laurenechan** [comment]
@LCCarmody Looking some more through gene reviews, we may also include some of these terms to our nutrition intake avoidance pattern:

Refsum disease
- [ ] phytanic acid restriction

Sitosterolemia
- [ ] plant sterol restriction 
- including: (vegetable oils, margarine, nuts, seeds, avocados, and chocolate)
- [ ] shellfish sterol restriction (specific type of cholesterol)

Primary trimethylaminuria
- [ ] restriction of Trimethylamine 
- (present in milk obtained from wheat-fed cows)
- [ ] restriction of choline 
- (present in eggs, liver, kidney, peas, beans, peanuts, soya products, and brassicas [Brussels sprouts, broccoli, cabbage, cauliflower]), 
- [ ] restriction of lecithin and lecithin-containing fish oil supplements
- [ ] restriction of Trimethylamine N-oxide (present in seafood [fish, cephalopods, and crustaceans]);
- [ ] restriction of Inhibitors of FMO3 enzyme activity such as indoles (found in brassicas).

Phosphoribosylpyrophosphate Synthetase Superactivity
- [ ] avoid high purine meats
- [ ] avoid shellfish
- [ ] avoid oily fish
- I know we have seafood product intake avoidance, would we like these specific terms?
- [ ] avoid beer
- [ ] avoid high fructose corn syrup

Lysinuric Protein Intolerance
- [ ] avoid excess nitrogen consumption

Pyruvate carboxylase deficiency
- [ ] avoid ketogenic diet

I was planning to still keep looking through gene reviews for more dietary avoidance/inclusion terms, but let me know if I should change my approach at all!

**Comment by LCCarmody** [comment]
Creating a CHEBI avoidance_of_food_intake pattern to take care of many of these terms.  DIet terms are being dealt with elsewhere.

**Comment by LCCarmody** [comment]
I have added many of these terms.  A handful of others have moved to other tickets or need to be longer discussions with the food community.
